window.esdocSearchIndex = [
  [
    "daylart/src/components/modals/addtolistmodal/index.tsx~addtolistmodal",
    "function/index.html#static-function-AddToListModal",
    "<span>AddToListModal</span> <span class=\"search-result-import-path\">daylart/src/components/Modals/AddToListModal/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponent/artistcomponent.tsx~artistcomponent",
    "function/index.html#static-function-ArtistComponent",
    "<span>ArtistComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponent/ArtistComponent.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponentgrid/artistgrid/index.tsx~artistgrid",
    "function/index.html#static-function-ArtistGrid",
    "<span>ArtistGrid</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/ArtistGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkcarouseldouble/index.tsx~artworkcarouseldouble",
    "function/index.html#static-function-ArtworkCarouselDouble",
    "<span>ArtworkCarouselDouble</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkCarouselDouble/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkcarouselsingle/index.tsx~artworkcarouselsingle",
    "function/index.html#static-function-ArtworkCarouselSingle",
    "<span>ArtworkCarouselSingle</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkCarouselSingle/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artwork/index.tsx~artworkcomponent",
    "function/index.html#static-function-ArtworkComponent",
    "<span>ArtworkComponent</span> <span class=\"search-result-import-path\">daylart/src/components/Artwork/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkgrid/index.tsx~artworkgrid",
    "function/index.html#static-function-ArtworkGrid",
    "<span>ArtworkGrid</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkgridtabview/index.tsx~artworkgridtabview",
    "function/index.html#static-function-ArtworkGridTabView",
    "<span>ArtworkGridTabView</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkGridTabView/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/moreinformation/artistmoreinfo/index.tsx~artworkmoreinfo",
    "function/index.html#static-function-ArtworkMoreInfo",
    "<span>ArtworkMoreInfo</span> <span class=\"search-result-import-path\">daylart/src/components/MoreInformation/ArtistMoreInfo/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/moreinformation/artworkmoreinfo/index.tsx~artworkmoreinfo",
    "function/index.html#static-function-ArtworkMoreInfo",
    "<span>ArtworkMoreInfo</span> <span class=\"search-result-import-path\">daylart/src/components/MoreInformation/ArtworkMoreInfo/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/backbutton/index.tsx~backbuttoncomponent",
    "function/index.html#static-function-BackButtonComponent",
    "<span>BackButtonComponent</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/BackButton/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/biographyinput/index.tsx~biographyinput",
    "function/index.html#static-function-BiographyInput",
    "<span>BiographyInput</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/BiographyInput/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/modals/colorpickermodal/index.tsx~colorpickermodal",
    "function/index.html#static-function-ColorPickerModal",
    "<span>ColorPickerModal</span> <span class=\"search-result-import-path\">daylart/src/components/Modals/ColorPickerModal/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/commentbar/index.tsx~commentbar",
    "function/index.html#static-function-CommentBar",
    "<span>CommentBar</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/CommentBar/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/credentialsinput/index.tsx~credentialsinputcomponent",
    "function/index.html#static-function-CredentialsInputComponent",
    "<span>CredentialsInputComponent</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/CredentialsInput/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/discoverbycolor/index.tsx~discoverbycolor",
    "function/index.html#static-function-DiscoverByColor",
    "<span>DiscoverByColor</span> <span class=\"search-result-import-path\">daylart/src/components/DiscoverByColor/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/modals/editlistmodal/index.tsx~editlistmodal",
    "function/index.html#static-function-EditListModal",
    "<span>EditListModal</span> <span class=\"search-result-import-path\">daylart/src/components/Modals/EditListModal/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/editprofile.tsx~editprofile",
    "function/index.html#static-function-EditProfile",
    "<span>EditProfile</span> <span class=\"search-result-import-path\">daylart/src/screens/EditProfile.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/editprofileinput/index.tsx~editprofileinput",
    "function/index.html#static-function-EditProfileInput",
    "<span>EditProfileInput</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/EditProfileInput/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/explorecomponent/index.tsx~explorecomponent",
    "function/index.html#static-function-ExploreComponent",
    "<span>ExploreComponent</span> <span class=\"search-result-import-path\">daylart/src/components/ExploreComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/explorepage.tsx~explorepage",
    "function/index.html#static-function-ExplorePage",
    "<span>ExplorePage</span> <span class=\"search-result-import-path\">daylart/src/screens/ExplorePage.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/filtermodal/index.tsx~filtermodal",
    "function/index.html#static-function-FilterModal",
    "<span>FilterModal</span> <span class=\"search-result-import-path\">daylart/src/components/FilterModal/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/headercomponent/headerartworkcomponent/index.tsx~header_max_height",
    "variable/index.html#static-variable-HEADER_MAX_HEIGHT",
    "<span>HEADER_MAX_HEIGHT</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderArtworkComponent/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/components/headercomponent/headereditprofilecomponent/index.tsx~header_max_height",
    "variable/index.html#static-variable-HEADER_MAX_HEIGHT",
    "<span>HEADER_MAX_HEIGHT</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/components/headercomponent/headereditprofilecomponent/index.tsx~header_min_height",
    "variable/index.html#static-variable-HEADER_MIN_HEIGHT",
    "<span>HEADER_MIN_HEIGHT</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/components/headercomponent/headereditprofilecomponent/index.tsx~header_scroll_distance",
    "variable/index.html#static-variable-HEADER_SCROLL_DISTANCE",
    "<span>HEADER_SCROLL_DISTANCE</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/components/headercomponent/headerartistnonusercomponent/index.tsx~headerartistnonuser",
    "function/index.html#static-function-HeaderArtistNonUser",
    "<span>HeaderArtistNonUser</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderArtistNonUserComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/headercomponent/headerartworkcomponent/index.tsx~headerartwork",
    "function/index.html#static-function-HeaderArtwork",
    "<span>HeaderArtwork</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderArtworkComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/detailedcomponents/headerdetailedpage/index.tsx~headerdetailedpage",
    "function/index.html#static-function-HeaderDetailedPage",
    "<span>HeaderDetailedPage</span> <span class=\"search-result-import-path\">daylart/src/components/DetailedComponents/HeaderDetailedPage/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/headercomponent/headereditprofilecomponent/index.tsx~headereditprofilecomponent",
    "function/index.html#static-function-HeaderEditProfileComponent",
    "<span>HeaderEditProfileComponent</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/headermainpage/index.tsx~headermainpage",
    "function/index.html#static-function-HeaderMainPage",
    "<span>HeaderMainPage</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/HeaderMainPage/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/headerpost/index.tsx~headerpost",
    "function/index.html#static-function-HeaderPost",
    "<span>HeaderPost</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/HeaderPost/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/headercomponent/headerusercomponent/index.tsx~headerusercomponent",
    "function/index.html#static-function-HeaderUserComponent",
    "<span>HeaderUserComponent</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderUserComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/headercomponent/headereditprofilecomponent/index.tsx~icon_transition",
    "variable/index.html#static-variable-ICON_TRANSITION",
    "<span>ICON_TRANSITION</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/services/constantes.ts~img1",
    "variable/index.html#static-variable-IMG1",
    "<span>IMG1</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/services/constantes.ts~img2",
    "variable/index.html#static-variable-IMG2",
    "<span>IMG2</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/imagepickercomponent/index.tsx~imagepickercomponent",
    "function/index.html#static-function-ImagePickerComponent",
    "<span>ImagePickerComponent</span> <span class=\"search-result-import-path\">daylart/src/components/ImagePickerComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/loadingscreen/index.tsx~index",
    "function/index.html#static-function-Index",
    "<span>Index</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/LoadingScreen/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/informations/index.tsx~information",
    "function/index.html#static-function-Information",
    "<span>Information</span> <span class=\"search-result-import-path\">daylart/src/components/Informations/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/services/constantes.ts~login",
    "variable/index.html#static-variable-LOGIN",
    "<span>LOGIN</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/services/constantes.ts~lorem",
    "variable/index.html#static-variable-LOREM",
    "<span>LOREM</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/artworkcarouseldouble/likedartworkscarousel/index.tsx~likedartworkscarousel",
    "function/index.html#static-function-LikedArtworksCarousel",
    "<span>LikedArtworksCarousel</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkCarouselDouble/LikedArtworksCarousel/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponent/listcomponent.tsx~listcomponent",
    "function/index.html#static-function-ListComponent",
    "<span>ListComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponent/ListComponent.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/listcontentpage.tsx~listcontentpage",
    "function/index.html#static-function-ListContentPage",
    "<span>ListContentPage</span> <span class=\"search-result-import-path\">daylart/src/screens/ListContentPage.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponentgrid/listgrid/index.tsx~listgridcomponent",
    "function/index.html#static-function-ListGridComponent",
    "<span>ListGridComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/ListGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/login.tsx~loginscreen",
    "function/index.html#static-function-LoginScreen",
    "<span>LoginScreen</span> <span class=\"search-result-import-path\">daylart/src/screens/Login.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkgrid/matchingbycolorgrid/index.tsx~matchingbycolorgrid",
    "function/index.html#static-function-MatchingByColorGrid",
    "<span>MatchingByColorGrid</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkGrid/MatchingByColorGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/matchingbycolorpage.tsx~matchingbycolorpage",
    "function/index.html#static-function-MatchingByColorPage",
    "<span>MatchingByColorPage</span> <span class=\"search-result-import-path\">daylart/src/screens/MatchingByColorPage.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/messagegrid/index.tsx~messagegrid",
    "function/index.html#static-function-MessageGrid",
    "<span>MessageGrid</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/MessageGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/messagepreview/index.tsx~messagepreviewcomponent",
    "function/index.html#static-function-MessagePreviewComponent",
    "<span>MessagePreviewComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/MessagePreview/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/modals/matchingimage/index.tsx~modalmatchingimage",
    "function/index.html#static-function-ModalMatchingImage",
    "<span>ModalMatchingImage</span> <span class=\"search-result-import-path\">daylart/src/components/Modals/MatchingImage/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/moreinformation/index.tsx~moreinformation",
    "function/index.html#static-function-MoreInformation",
    "<span>MoreInformation</span> <span class=\"search-result-import-path\">daylart/src/components/MoreInformation/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkcarouseldouble/mostmatched/index.tsx~mostmatchedcomponent",
    "function/index.html#static-function-MostMatchedComponent",
    "<span>MostMatchedComponent</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkCarouselDouble/MostMatched/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponentgrid/myartists/index.tsx~mylikedartists",
    "function/index.html#static-function-MyLikedArtists",
    "<span>MyLikedArtists</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/MyArtists/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponentgrid/mylists/index.tsx~mylistscomponent",
    "function/index.html#static-function-MyListsComponent",
    "<span>MyListsComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/MyLists/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/myprofile.tsx~myprofile",
    "function/index.html#static-function-MyProfile",
    "<span>MyProfile</span> <span class=\"search-result-import-path\">daylart/src/screens/MyProfile.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/modals/newlistmodal/index.tsx~newlistmodal",
    "function/index.html#static-function-NewListModal",
    "<span>NewListModal</span> <span class=\"search-result-import-path\">daylart/src/components/Modals/NewListModal/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/newpost/newpostbutton/index.tsx~newpostbutton",
    "function/index.html#static-function-NewPostButton",
    "<span>NewPostButton</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/NewPost/NewPostButton/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/newpost/newpostheader/index.tsx~newpostheader",
    "function/index.html#static-function-NewPostHeader",
    "<span>NewPostHeader</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/NewPost/NewPostHeader/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/newpost/newposttext/index.tsx~newposttext",
    "function/index.html#static-function-NewPostText",
    "<span>NewPostText</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/NewPost/NewPostText/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/newsearchbar/index.tsx~newsearchbar",
    "function/index.html#static-function-NewSearchBar",
    "<span>NewSearchBar</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/NewSearchBar/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/notifications/notificationcomponent/index.tsx~notificationcomponent",
    "function/index.html#static-function-NotificationComponent",
    "<span>NotificationComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/Notifications/NotificationComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/notifications/notificationgrid/index.tsx~notificationgrid",
    "function/index.html#static-function-NotificationGrid",
    "<span>NotificationGrid</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/Notifications/NotificationGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/oldartistpage.tsx~oldartistpage",
    "function/index.html#static-function-OldArtistPage",
    "<span>OldArtistPage</span> <span class=\"search-result-import-path\">daylart/src/screens/OldArtistPage.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/onclickimage/index.tsx~onclickimagecomponent",
    "function/index.html#static-function-OnClickImageComponent",
    "<span>OnClickImageComponent</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/OnClickImage/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/optioncomponent/index.tsx~optioncomponent",
    "function/index.html#static-function-OptionComponent",
    "<span>OptionComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/OptionComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/services/constantes.ts~pp1",
    "variable/index.html#static-variable-PP1",
    "<span>PP1</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/services/constantes.ts~pp2",
    "variable/index.html#static-variable-PP2",
    "<span>PP2</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/artworkcarouseldouble/paintingsfromsameartist/index.tsx~paintingsfromsameartistcomponent",
    "function/index.html#static-function-PaintingsFromSameArtistComponent",
    "<span>PaintingsFromSameArtistComponent</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkCarouselDouble/PaintingsFromSameArtist/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/artworkcarouseldouble/matchedpainting/index.tsx~paintingsmatchedfromsource",
    "function/index.html#static-function-PaintingsMatchedFromSource",
    "<span>PaintingsMatchedFromSource</span> <span class=\"search-result-import-path\">daylart/src/components/ArtworkCarouselDouble/MatchedPainting/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/postanalysis/index.tsx~postanalysis",
    "function/index.html#static-function-PostAnalysis",
    "<span>PostAnalysis</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/PostAnalysis/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/postcomment/index.tsx~postcomment",
    "function/index.html#static-function-PostComment",
    "<span>PostComment</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/PostComment/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/postpainting/index.tsx~postpainting",
    "function/index.html#static-function-PostPainting",
    "<span>PostPainting</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/PostPainting/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/postsocial/index.tsx~postsocial",
    "function/index.html#static-function-PostSocial",
    "<span>PostSocial</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/PostSocial/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/services/constantes.ts~reload",
    "variable/index.html#static-variable-RELOAD",
    "<span>RELOAD</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/squarecomponentgrid/randomartists/index.tsx~randomartists",
    "function/index.html#static-function-RandomArtists",
    "<span>RandomArtists</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/RandomArtists/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/repostpost/index.tsx~repostpost",
    "function/index.html#static-function-RepostPost",
    "<span>RepostPost</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/RepostPost/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/services/constantes.ts~salt",
    "variable/index.html#static-variable-SALT",
    "<span>SALT</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/services/constantes.ts~signup",
    "variable/index.html#static-variable-SIGNUP",
    "<span>SIGNUP</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/headercomponent/headereditprofilecomponent/index.tsx~substract_start_transition",
    "variable/index.html#static-variable-SUBSTRACT_START_TRANSITION",
    "<span>SUBSTRACT_START_TRANSITION</span> <span class=\"search-result-import-path\">daylart/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/components/searchartworkgridcomponent/index.tsx~searchartworkgridcomponent",
    "function/index.html#static-function-SearchArtworkGridComponent",
    "<span>SearchArtworkGridComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SearchArtworkGridComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/signup.tsx~signupscreen",
    "function/index.html#static-function-SignUpScreen",
    "<span>SignUpScreen</span> <span class=\"search-result-import-path\">daylart/src/screens/SignUp.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponentgrid/similarartists/index.tsx~similarartists",
    "function/index.html#static-function-SimilarArtists",
    "<span>SimilarArtists</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/SimilarArtists/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/searchbar/smallersearchbar.tsx~smallersearchbar",
    "function/index.html#static-function-SmallerSearchBar",
    "<span>SmallerSearchBar</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/SearchBar/SmallerSearchBar.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/squarecomponentgrid/index.tsx~squarecomponentgrid",
    "function/index.html#static-function-SquareComponentGrid",
    "<span>SquareComponentGrid</span> <span class=\"search-result-import-path\">daylart/src/components/SquareComponentGrid/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/tag/index.tsx~tag",
    "function/index.html#static-function-Tag",
    "<span>Tag</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/Tag/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/threedotscomponent/index.tsx~threedotscomponent",
    "function/index.html#static-function-ThreeDotsComponent",
    "<span>ThreeDotsComponent</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/ThreeDotsComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/modals/threedotsprofilemodal/index.tsx~threedotsprofilemodal",
    "function/index.html#static-function-ThreeDotsProfileModal",
    "<span>ThreeDotsProfileModal</span> <span class=\"search-result-import-path\">daylart/src/components/Modals/ThreeDotsProfileModal/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/toastcomponent/index.tsx~toastcomponent",
    "function/index.html#static-function-ToastComponent",
    "<span>ToastComponent</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/ToastComponent/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/utilities/toolbarlistpage/index.tsx~toolbarlistpage",
    "function/index.html#static-function-ToolBarListPage",
    "<span>ToolBarListPage</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/ToolBarListPage/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/toolbarpainting/index.tsx~toolbarpainting",
    "function/index.html#static-function-ToolBarPainting",
    "<span>ToolBarPainting</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/ToolBarPainting/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/components/socialnetwork/toolbarpost/index.tsx~toolbarpost",
    "function/index.html#static-function-ToolBarPost",
    "<span>ToolBarPost</span> <span class=\"search-result-import-path\">daylart/src/components/SocialNetwork/ToolBarPost/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/services/constantes.ts~url",
    "variable/index.html#static-variable-URL",
    "<span>URL</span> <span class=\"search-result-import-path\">daylart/src/services/constantes.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/userdata/index.tsx~userdata",
    "function/index.html#static-function-UserData",
    "<span>UserData</span> <span class=\"search-result-import-path\">daylart/src/components/UserData/index.tsx</span>",
    "function"
  ],
  [
    "daylart/src/screens/welcomescreen.tsx~welcomescreen",
    "function/index.html#static-function-WelcomeScreen",
    "<span>WelcomeScreen</span> <span class=\"search-result-import-path\">daylart/src/screens/WelcomeScreen.tsx</span>",
    "function"
  ],
  [
    "daylart/src/services/authservice.ts~authservice",
    "variable/index.html#static-variable-authService",
    "<span>authService</span> <span class=\"search-result-import-path\">daylart/src/services/authService.ts</span>",
    "variable"
  ],
  [
    "daylart/src/components/discoverbycolor/index.tsx~randomcolor",
    "variable/index.html#static-variable-randomColor",
    "<span>randomColor</span> <span class=\"search-result-import-path\">daylart/src/components/DiscoverByColor/index.tsx</span>",
    "variable"
  ],
  [
    "daylart/src/components/utilities/toastcomponent/index.tsx~toastconfig",
    "variable/index.html#static-variable-toastConfig",
    "<span>toastConfig</span> <span class=\"search-result-import-path\">daylart/src/components/Utilities/ToastComponent/index.tsx</span>",
    "variable"
  ],
  [
    "src/components/artwork/index.tsx",
    "file/src/components/Artwork/index.tsx.html",
    "src/components/Artwork/index.tsx",
    "file"
  ],
  [
    "src/components/artworkcarouseldouble/likedartworkscarousel/index.tsx",
    "file/src/components/ArtworkCarouselDouble/LikedArtworksCarousel/index.tsx.html",
    "src/components/ArtworkCarouselDouble/LikedArtworksCarousel/index.tsx",
    "file"
  ],
  [
    "src/components/artworkcarouseldouble/matchedpainting/index.tsx",
    "file/src/components/ArtworkCarouselDouble/MatchedPainting/index.tsx.html",
    "src/components/ArtworkCarouselDouble/MatchedPainting/index.tsx",
    "file"
  ],
  [
    "src/components/artworkcarouseldouble/mostmatched/index.tsx",
    "file/src/components/ArtworkCarouselDouble/MostMatched/index.tsx.html",
    "src/components/ArtworkCarouselDouble/MostMatched/index.tsx",
    "file"
  ],
  [
    "src/components/artworkcarouseldouble/paintingsfromsameartist/index.tsx",
    "file/src/components/ArtworkCarouselDouble/PaintingsFromSameArtist/index.tsx.html",
    "src/components/ArtworkCarouselDouble/PaintingsFromSameArtist/index.tsx",
    "file"
  ],
  [
    "src/components/artworkcarouseldouble/index.tsx",
    "file/src/components/ArtworkCarouselDouble/index.tsx.html",
    "src/components/ArtworkCarouselDouble/index.tsx",
    "file"
  ],
  [
    "src/components/artworkcarouselsingle/index.tsx",
    "file/src/components/ArtworkCarouselSingle/index.tsx.html",
    "src/components/ArtworkCarouselSingle/index.tsx",
    "file"
  ],
  [
    "src/components/artworkgrid/matchingbycolorgrid/index.tsx",
    "file/src/components/ArtworkGrid/MatchingByColorGrid/index.tsx.html",
    "src/components/ArtworkGrid/MatchingByColorGrid/index.tsx",
    "file"
  ],
  [
    "src/components/artworkgrid/index.tsx",
    "file/src/components/ArtworkGrid/index.tsx.html",
    "src/components/ArtworkGrid/index.tsx",
    "file"
  ],
  [
    "src/components/artworkgridtabview/index.tsx",
    "file/src/components/ArtworkGridTabView/index.tsx.html",
    "src/components/ArtworkGridTabView/index.tsx",
    "file"
  ],
  [
    "src/components/detailedcomponents/headerdetailedpage/index.tsx",
    "file/src/components/DetailedComponents/HeaderDetailedPage/index.tsx.html",
    "src/components/DetailedComponents/HeaderDetailedPage/index.tsx",
    "file"
  ],
  [
    "src/components/discoverbycolor/index.tsx",
    "file/src/components/DiscoverByColor/index.tsx.html",
    "src/components/DiscoverByColor/index.tsx",
    "file"
  ],
  [
    "src/components/explorecomponent/index.tsx",
    "file/src/components/ExploreComponent/index.tsx.html",
    "src/components/ExploreComponent/index.tsx",
    "file"
  ],
  [
    "src/components/filtermodal/index.tsx",
    "file/src/components/FilterModal/index.tsx.html",
    "src/components/FilterModal/index.tsx",
    "file"
  ],
  [
    "src/components/headercomponent/headerartistnonusercomponent/index.tsx",
    "file/src/components/HeaderComponent/HeaderArtistNonUserComponent/index.tsx.html",
    "src/components/HeaderComponent/HeaderArtistNonUserComponent/index.tsx",
    "file"
  ],
  [
    "src/components/headercomponent/headerartworkcomponent/index.tsx",
    "file/src/components/HeaderComponent/HeaderArtworkComponent/index.tsx.html",
    "src/components/HeaderComponent/HeaderArtworkComponent/index.tsx",
    "file"
  ],
  [
    "src/components/headercomponent/headereditprofilecomponent/index.tsx",
    "file/src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx.html",
    "src/components/HeaderComponent/HeaderEditProfileComponent/index.tsx",
    "file"
  ],
  [
    "src/components/headercomponent/headerusercomponent/index.tsx",
    "file/src/components/HeaderComponent/HeaderUserComponent/index.tsx.html",
    "src/components/HeaderComponent/HeaderUserComponent/index.tsx",
    "file"
  ],
  [
    "src/components/imagepickercomponent/index.tsx",
    "file/src/components/ImagePickerComponent/index.tsx.html",
    "src/components/ImagePickerComponent/index.tsx",
    "file"
  ],
  [
    "src/components/informations/index.tsx",
    "file/src/components/Informations/index.tsx.html",
    "src/components/Informations/index.tsx",
    "file"
  ],
  [
    "src/components/locationpickercomponent/index.tsx",
    "file/src/components/LocationPickerComponent/index.tsx.html",
    "src/components/LocationPickerComponent/index.tsx",
    "file"
  ],
  [
    "src/components/modals/addtolistmodal/index.tsx",
    "file/src/components/Modals/AddToListModal/index.tsx.html",
    "src/components/Modals/AddToListModal/index.tsx",
    "file"
  ],
  [
    "src/components/modals/colorpickermodal/index.tsx",
    "file/src/components/Modals/ColorPickerModal/index.tsx.html",
    "src/components/Modals/ColorPickerModal/index.tsx",
    "file"
  ],
  [
    "src/components/modals/editlistmodal/index.tsx",
    "file/src/components/Modals/EditListModal/index.tsx.html",
    "src/components/Modals/EditListModal/index.tsx",
    "file"
  ],
  [
    "src/components/modals/matchingimage/index.tsx",
    "file/src/components/Modals/MatchingImage/index.tsx.html",
    "src/components/Modals/MatchingImage/index.tsx",
    "file"
  ],
  [
    "src/components/modals/newlistmodal/index.tsx",
    "file/src/components/Modals/NewListModal/index.tsx.html",
    "src/components/Modals/NewListModal/index.tsx",
    "file"
  ],
  [
    "src/components/modals/threedotsprofilemodal/index.tsx",
    "file/src/components/Modals/ThreeDotsProfileModal/index.tsx.html",
    "src/components/Modals/ThreeDotsProfileModal/index.tsx",
    "file"
  ],
  [
    "src/components/moreinformation/artistmoreinfo/index.tsx",
    "file/src/components/MoreInformation/ArtistMoreInfo/index.tsx.html",
    "src/components/MoreInformation/ArtistMoreInfo/index.tsx",
    "file"
  ],
  [
    "src/components/moreinformation/artworkmoreinfo/index.tsx",
    "file/src/components/MoreInformation/ArtworkMoreInfo/index.tsx.html",
    "src/components/MoreInformation/ArtworkMoreInfo/index.tsx",
    "file"
  ],
  [
    "src/components/moreinformation/index.tsx",
    "file/src/components/MoreInformation/index.tsx.html",
    "src/components/MoreInformation/index.tsx",
    "file"
  ],
  [
    "src/components/searchartworkgridcomponent/index.tsx",
    "file/src/components/SearchArtworkGridComponent/index.tsx.html",
    "src/components/SearchArtworkGridComponent/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/commentbar/index.tsx",
    "file/src/components/SocialNetwork/CommentBar/index.tsx.html",
    "src/components/SocialNetwork/CommentBar/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/headermainpage/index.tsx",
    "file/src/components/SocialNetwork/HeaderMainPage/index.tsx.html",
    "src/components/SocialNetwork/HeaderMainPage/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/headerpost/index.tsx",
    "file/src/components/SocialNetwork/HeaderPost/index.tsx.html",
    "src/components/SocialNetwork/HeaderPost/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/messagegrid/index.tsx",
    "file/src/components/SocialNetwork/MessageGrid/index.tsx.html",
    "src/components/SocialNetwork/MessageGrid/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/messagepreview/index.tsx",
    "file/src/components/SocialNetwork/MessagePreview/index.tsx.html",
    "src/components/SocialNetwork/MessagePreview/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/newpost/newpostbutton/index.tsx",
    "file/src/components/SocialNetwork/NewPost/NewPostButton/index.tsx.html",
    "src/components/SocialNetwork/NewPost/NewPostButton/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/newpost/newpostheader/index.tsx",
    "file/src/components/SocialNetwork/NewPost/NewPostHeader/index.tsx.html",
    "src/components/SocialNetwork/NewPost/NewPostHeader/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/newpost/newposttext/index.tsx",
    "file/src/components/SocialNetwork/NewPost/NewPostText/index.tsx.html",
    "src/components/SocialNetwork/NewPost/NewPostText/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/notifications/notificationcomponent/index.tsx",
    "file/src/components/SocialNetwork/Notifications/NotificationComponent/index.tsx.html",
    "src/components/SocialNetwork/Notifications/NotificationComponent/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/notifications/notificationgrid/index.tsx",
    "file/src/components/SocialNetwork/Notifications/NotificationGrid/index.tsx.html",
    "src/components/SocialNetwork/Notifications/NotificationGrid/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/optioncomponent/index.tsx",
    "file/src/components/SocialNetwork/OptionComponent/index.tsx.html",
    "src/components/SocialNetwork/OptionComponent/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/postanalysis/index.tsx",
    "file/src/components/SocialNetwork/PostAnalysis/index.tsx.html",
    "src/components/SocialNetwork/PostAnalysis/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/postcomment/index.tsx",
    "file/src/components/SocialNetwork/PostComment/index.tsx.html",
    "src/components/SocialNetwork/PostComment/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/postpainting/index.tsx",
    "file/src/components/SocialNetwork/PostPainting/index.tsx.html",
    "src/components/SocialNetwork/PostPainting/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/postsocial/index.tsx",
    "file/src/components/SocialNetwork/PostSocial/index.tsx.html",
    "src/components/SocialNetwork/PostSocial/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/repostpost/index.tsx",
    "file/src/components/SocialNetwork/RepostPost/index.tsx.html",
    "src/components/SocialNetwork/RepostPost/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/threedotscomponent/index.tsx",
    "file/src/components/SocialNetwork/ThreeDotsComponent/index.tsx.html",
    "src/components/SocialNetwork/ThreeDotsComponent/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/toolbarpainting/index.tsx",
    "file/src/components/SocialNetwork/ToolBarPainting/index.tsx.html",
    "src/components/SocialNetwork/ToolBarPainting/index.tsx",
    "file"
  ],
  [
    "src/components/socialnetwork/toolbarpost/index.tsx",
    "file/src/components/SocialNetwork/ToolBarPost/index.tsx.html",
    "src/components/SocialNetwork/ToolBarPost/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponent/artistcomponent.tsx",
    "file/src/components/SquareComponent/ArtistComponent.tsx.html",
    "src/components/SquareComponent/ArtistComponent.tsx",
    "file"
  ],
  [
    "src/components/squarecomponent/listcomponent.tsx",
    "file/src/components/SquareComponent/ListComponent.tsx.html",
    "src/components/SquareComponent/ListComponent.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/artistgrid/index.tsx",
    "file/src/components/SquareComponentGrid/ArtistGrid/index.tsx.html",
    "src/components/SquareComponentGrid/ArtistGrid/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/listgrid/index.tsx",
    "file/src/components/SquareComponentGrid/ListGrid/index.tsx.html",
    "src/components/SquareComponentGrid/ListGrid/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/myartists/index.tsx",
    "file/src/components/SquareComponentGrid/MyArtists/index.tsx.html",
    "src/components/SquareComponentGrid/MyArtists/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/mylists/index.tsx",
    "file/src/components/SquareComponentGrid/MyLists/index.tsx.html",
    "src/components/SquareComponentGrid/MyLists/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/randomartists/index.tsx",
    "file/src/components/SquareComponentGrid/RandomArtists/index.tsx.html",
    "src/components/SquareComponentGrid/RandomArtists/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/similarartists/index.tsx",
    "file/src/components/SquareComponentGrid/SimilarArtists/index.tsx.html",
    "src/components/SquareComponentGrid/SimilarArtists/index.tsx",
    "file"
  ],
  [
    "src/components/squarecomponentgrid/index.tsx",
    "file/src/components/SquareComponentGrid/index.tsx.html",
    "src/components/SquareComponentGrid/index.tsx",
    "file"
  ],
  [
    "src/components/userdata/index.tsx",
    "file/src/components/UserData/index.tsx.html",
    "src/components/UserData/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/backbutton/index.tsx",
    "file/src/components/Utilities/BackButton/index.tsx.html",
    "src/components/Utilities/BackButton/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/biographyinput/index.tsx",
    "file/src/components/Utilities/BiographyInput/index.tsx.html",
    "src/components/Utilities/BiographyInput/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/credentialsinput/index.tsx",
    "file/src/components/Utilities/CredentialsInput/index.tsx.html",
    "src/components/Utilities/CredentialsInput/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/editprofileinput/index.tsx",
    "file/src/components/Utilities/EditProfileInput/index.tsx.html",
    "src/components/Utilities/EditProfileInput/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/loadingscreen/index.tsx",
    "file/src/components/Utilities/LoadingScreen/index.tsx.html",
    "src/components/Utilities/LoadingScreen/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/newsearchbar/index.tsx",
    "file/src/components/Utilities/NewSearchBar/index.tsx.html",
    "src/components/Utilities/NewSearchBar/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/onclickimage/index.tsx",
    "file/src/components/Utilities/OnClickImage/index.tsx.html",
    "src/components/Utilities/OnClickImage/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/searchbar/smallersearchbar.tsx",
    "file/src/components/Utilities/SearchBar/SmallerSearchBar.tsx.html",
    "src/components/Utilities/SearchBar/SmallerSearchBar.tsx",
    "file"
  ],
  [
    "src/components/utilities/searchbar/index.tsx",
    "file/src/components/Utilities/SearchBar/index.tsx.html",
    "src/components/Utilities/SearchBar/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/tag/index.tsx",
    "file/src/components/Utilities/Tag/index.tsx.html",
    "src/components/Utilities/Tag/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/toastcomponent/index.tsx",
    "file/src/components/Utilities/ToastComponent/index.tsx.html",
    "src/components/Utilities/ToastComponent/index.tsx",
    "file"
  ],
  [
    "src/components/utilities/toolbarlistpage/index.tsx",
    "file/src/components/Utilities/ToolBarListPage/index.tsx.html",
    "src/components/Utilities/ToolBarListPage/index.tsx",
    "file"
  ],
  [
    "src/screens/artistnonuserpage.tsx",
    "file/src/screens/ArtistNonUserPage.tsx.html",
    "src/screens/ArtistNonUserPage.tsx",
    "file"
  ],
  [
    "src/screens/commentspage.tsx",
    "file/src/screens/CommentsPage.tsx.html",
    "src/screens/CommentsPage.tsx",
    "file"
  ],
  [
    "src/screens/detailedscreensquarecomponents.tsx",
    "file/src/screens/DetailedScreenSquareComponents.tsx.html",
    "src/screens/DetailedScreenSquareComponents.tsx",
    "file"
  ],
  [
    "src/screens/editprofile.tsx",
    "file/src/screens/EditProfile.tsx.html",
    "src/screens/EditProfile.tsx",
    "file"
  ],
  [
    "src/screens/explorepage.tsx",
    "file/src/screens/ExplorePage.tsx.html",
    "src/screens/ExplorePage.tsx",
    "file"
  ],
  [
    "src/screens/homescreen.tsx",
    "file/src/screens/HomeScreen.tsx.html",
    "src/screens/HomeScreen.tsx",
    "file"
  ],
  [
    "src/screens/imagepickertest.tsx",
    "file/src/screens/ImagePickerTest.tsx.html",
    "src/screens/ImagePickerTest.tsx",
    "file"
  ],
  [
    "src/screens/listcontentpage.tsx",
    "file/src/screens/ListContentPage.tsx.html",
    "src/screens/ListContentPage.tsx",
    "file"
  ],
  [
    "src/screens/login.tsx",
    "file/src/screens/Login.tsx.html",
    "src/screens/Login.tsx",
    "file"
  ],
  [
    "src/screens/matchingbycolorpage.tsx",
    "file/src/screens/MatchingByColorPage.tsx.html",
    "src/screens/MatchingByColorPage.tsx",
    "file"
  ],
  [
    "src/screens/messagespage.tsx",
    "file/src/screens/MessagesPage.tsx.html",
    "src/screens/MessagesPage.tsx",
    "file"
  ],
  [
    "src/screens/modalscreen.tsx",
    "file/src/screens/ModalScreen.tsx.html",
    "src/screens/ModalScreen.tsx",
    "file"
  ],
  [
    "src/screens/myprofile.tsx",
    "file/src/screens/MyProfile.tsx.html",
    "src/screens/MyProfile.tsx",
    "file"
  ],
  [
    "src/screens/newpostpage.tsx",
    "file/src/screens/NewPostPage.tsx.html",
    "src/screens/NewPostPage.tsx",
    "file"
  ],
  [
    "src/screens/notfoundscreen.tsx",
    "file/src/screens/NotFoundScreen.tsx.html",
    "src/screens/NotFoundScreen.tsx",
    "file"
  ],
  [
    "src/screens/notificationspage.tsx",
    "file/src/screens/NotificationsPage.tsx.html",
    "src/screens/NotificationsPage.tsx",
    "file"
  ],
  [
    "src/screens/oldartistpage.tsx",
    "file/src/screens/OldArtistPage.tsx.html",
    "src/screens/OldArtistPage.tsx",
    "file"
  ],
  [
    "src/screens/signup.tsx",
    "file/src/screens/SignUp.tsx.html",
    "src/screens/SignUp.tsx",
    "file"
  ],
  [
    "src/screens/tabonescreen.tsx",
    "file/src/screens/TabOneScreen.tsx.html",
    "src/screens/TabOneScreen.tsx",
    "file"
  ],
  [
    "src/screens/tabtwoscreen.tsx",
    "file/src/screens/TabTwoScreen.tsx.html",
    "src/screens/TabTwoScreen.tsx",
    "file"
  ],
  [
    "src/screens/threedotspage.tsx",
    "file/src/screens/ThreeDotsPage.tsx.html",
    "src/screens/ThreeDotsPage.tsx",
    "file"
  ],
  [
    "src/screens/welcomescreen.tsx",
    "file/src/screens/WelcomeScreen.tsx.html",
    "src/screens/WelcomeScreen.tsx",
    "file"
  ],
  [
    "src/services/authservice.ts",
    "file/src/services/authService.ts.html",
    "src/services/authService.ts",
    "file"
  ],
  [
    "src/services/constantes.ts",
    "file/src/services/constantes.ts.html",
    "src/services/constantes.ts",
    "file"
  ]
]